import { createContext } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', localName: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'es', name: 'Spanish', localName: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'fr', name: 'French', localName: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', name: 'German', localName: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', localName: 'Português', flag: '🇵🇹', dir: 'ltr' },
  { code: 'it', name: 'Italian', localName: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'ru', name: 'Russian', localName: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', localName: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'hi', name: 'Hindi', localName: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'bn', name: 'Bengali', localName: 'বাংলা', flag: '🇧🇩', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', localName: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'ko', name: 'Korean', localName: '한국어', flag: '🇰🇷', dir: 'ltr' },
  { code: 'zh', name: 'Chinese (Simplified)', localName: '简体中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', localName: '繁體中文', flag: '🇹🇼', dir: 'ltr' },
  { code: 'tr', name: 'Turkish', localName: 'Türkçe', flag: '🇹🇷', dir: 'ltr' },
  { code: 'nl', name: 'Dutch', localName: 'Nederlands', flag: '🇳🇱', dir: 'ltr' },
  { code: 'pl', name: 'Polish', localName: 'Polski', flag: '🇵🇱', dir: 'ltr' },
  { code: 'uk', name: 'Ukrainian', localName: 'Українська', flag: '🇺🇦', dir: 'ltr' },
  { code: 'vi', name: 'Vietnamese', localName: 'Tiếng Việt', flag: '🇻🇳', dir: 'ltr' },
  { code: 'th', name: 'Thai', localName: 'ไทย', flag: '🇹🇭', dir: 'ltr' },
  { code: 'id', name: 'Indonesian', localName: 'Bahasa Indonesia', flag: '🇮🇩', dir: 'ltr' },
  { code: 'ms', name: 'Malay', localName: 'Bahasa Melayu', flag: '🇲🇾', dir: 'ltr' },
  { code: 'ta', name: 'Tamil', localName: 'தமிழ்', flag: '🇱🇰', dir: 'ltr' },
  { code: 'te', name: 'Telugu', localName: 'తెలుగు', flag: '🇮🇳', dir: 'ltr' },
  { code: 'mr', name: 'Marathi', localName: 'मраठी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'gu', name: 'Gujarati', localName: 'ગુજરાતી', flag: '🇮🇳', dir: 'ltr' },
  { code: 'pa', name: 'Punjabi', localName: 'ਪੰਜਾਬੀ', flag: '🇮🇳', dir: 'ltr' },
  { code: 'ur', name: 'Urdu', localName: 'اردو', flag: '🇵🇰', dir: 'rtl' },
  { code: 'fa', name: 'Persian', localName: 'فارسی', flag: '🇮🇷', dir: 'rtl' },
  { code: 'he', name: 'Hebrew', localName: 'עברית', flag: '🇮🇱', dir: 'rtl' },
  { code: 'sw', name: 'Swahili', localName: 'Kiswahili', flag: '🇰🇪', dir: 'ltr' },
  { code: 'el', name: 'Greek', localName: 'Ελληνικά', flag: '🇬🇷', dir: 'ltr' },
  { code: 'ro', name: 'Romanian', localName: 'Română', flag: '🇷🇴', dir: 'ltr' },
  { code: 'cs', name: 'Czech', localName: 'Čeština', flag: '🇨🇿', dir: 'ltr' },
  { code: 'hu', name: 'Hungarian', localName: 'Magyar', flag: '🇭🇺', dir: 'ltr' },
  { code: 'da', name: 'Danish', localName: 'Dansk', flag: '🇩🇰', dir: 'ltr' },
  { code: 'fi', name: 'Finnish', localName: 'Suomi', flag: '🇫🇮', dir: 'ltr' },
  { code: 'no', name: 'Norwegian', localName: 'Norsk', flag: '🇳🇴', dir: 'ltr' },
  { code: 'sv', name: 'Swedish', localName: 'Svenska', flag: '🇸🇪', dir: 'ltr' },
  { code: 'sk', name: 'Slovak', localName: 'Slovenčina', flag: '🇸🇰', dir: 'ltr' },
  { code: 'hr', name: 'Croatian', localName: 'Hrvatski', flag: '🇭🇷', dir: 'ltr' },
  { code: 'sr', name: 'Serbian', localName: 'Српски', flag: '🇷🇸', dir: 'ltr' },
  { code: 'bg', name: 'Bulgarian', localName: 'Български', flag: '🇧🇬', dir: 'ltr' },
  { code: 'lt', name: 'Lithuanian', localName: 'Lietuvių', flag: '🇱🇹', dir: 'ltr' },
  { code: 'lv', name: 'Latvian', localName: 'Latviešu', flag: '🇱🇻', dir: 'ltr' },
  { code: 'et', name: 'Estonian', localName: 'Eesti', flag: '🇪🇪', dir: 'ltr' },
  { code: 'fil', name: 'Filipino', localName: 'Filipino', flag: '🇵🇭', dir: 'ltr' },
  { code: 'si', name: 'Sinhala', localName: 'සිංහල', flag: '🇱🇰', dir: 'ltr' },
  { code: 'ne', name: 'Nepali', localName: 'नेपाली', flag: '🇳🇵', dir: 'ltr' }
];

export const LanguageContext = createContext();
